# Analysis file for Dart Analyzer
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
